#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0
# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
# BeastHost
if [ -z "${BEAST_HOST}" ]; then
  echo "ERROR: BEAST_HOST environment variable not set"
  EXITCODE=1
fi
# Handle "-e LATITUDE"
if [ -z "${LATITUDE}" ]; then
  echo "ERROR: LATITUDE environment variable not set"
  EXITCODE=1
fi
# Handle "-e LONGITUDE"
if [ -z "${LONGITUDE}" ]; then
  echo "ERROR: LONGITUDE environment variable not set"
  EXITCODE=1
fi
# All is good ?
if [ $EXITCODE == 0 ]; then
  # shellcheck disable=SC2153
  echo "INFO: Connect to ${BEAST_HOST}:${BEAST_PORT}"
fi

exit $EXITCODE
