#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2034

# Define bash colours
NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'
CYAN='\033[0;36m'
#YELLOW='\033[1;33m'

EXITCODE=0
# Handle "-e LAT"
if [ -z "${LAT}" ]; then
  echo -e "${LIGHTRED}ERROR: LAT environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e LON"
if [ -z "${LON}" ]; then
  echo -e "${LIGHTRED}ERROR: LON environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e BEAST_HOST"
if [ -z "${BEAST_HOST}" ]; then
  echo -e "${LIGHTRED}ERROR: BEAST_HOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e BEAST_PORT"
if [ -z "${BEAST_PORT}" ]; then
  echo -e "${LIGHTRED}ERROR: BEAST_PORT environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Error ?
if [ $EXITCODE -ne 0 ]; then
  exit 1
else
  echo -e "${CYAN}INFO: Connect to $BEAST_HOST:$BEAST_PORT${NOCOLOR}"
fi
# End
exit $EXITCODE
